% files = {'/Users/zhilianggong/Documents/MATLAB/XeRay/examples/bulk.xfluo', '/Users/zhilianggong/Documents/MATLAB/XeRay/examples/surf.xfluo'};
% this = XeRayGUI(files);
% a = this.data{1};
% b = this.data{2};
clc;
close all;
clear;
close all;
this = XeRayGUI2();
a = this;